services:
  files-md:
    build: .
    image: files-md
    ports:
      - "80:18081"
      # host:container, e.g. "80:18081"
    volumes:
      - storage:/app/storage
      - tokens:/app/tokens
    environment:
      APP_URL: http://localhost
      # API_URL: http://api.localhost # Uncomment if you want synchronization API
      STORAGE_DIR: /app/storage
      TOKENS_DIR: /app/tokens
    restart: unless-stopped

volumes:
  storage:
  tokens:
